---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openstack-dataplane-ansible-log
  namespace: openstack
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
