---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - https://github.com/openstack-gitops/rhoso-gitops/base/initialize/gitops/components/annotations?ref=main
resources:
  - ansible-logging-pvc.yaml
  - dataplane-deployment.yaml
  - preprovisioned-nodeset.yaml
